# Generated by Django 5.2.6 on 2025-11-15 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('restaurant', 'restaurant'), ('dish', 'dish'), ('both', 'both')], default='both', max_length=20)),
                ('group', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_ref', models.IntegerField(default=0)),
                ('dish_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_dishes', to='aplicacion.dishtype')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('price', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('url', models.URLField(blank=True, null=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuisines', models.ManyToManyField(blank=True, to='aplicacion.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kitchen', 'kitchen'), ('bathroom', 'bathroom'), ('tables', 'tables'), ('entrance', 'entrance'), ('menu', 'menu'), ('dish', 'dish'), ('other', 'other')], max_length=20)),
                ('category_label', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(max_length=300, upload_to='photos/')),
                ('taken_at', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='aplicacion.dish')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='aplicacion.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='aplicacion.restaurant'),
        ),
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.restaurant')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tag')),
            ],
            options={
                'unique_together': {('restaurant', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, through='aplicacion.RestaurantTag', to='aplicacion.tag'),
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_contamination', models.BooleanField(default=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.dish')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tag')),
            ],
            options={
                'unique_together': {('dish', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, through='aplicacion.DishTag', to='aplicacion.tag'),
        ),
        migrations.CreateModel(
            name='DishTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='aplicacion.dishtype')),
            ],
            options={
                'unique_together': {('dish_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aplicacion.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'created_at'], name='aplicacion__restaur_35dcb2_idx'), models.Index(fields=['user', 'created_at'], name='aplicacion__user_id_d55a01_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField(max_length=500)),
                ('price_paid', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aplicacion.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['dish', 'created_at'], name='aplicacion__dish_id_e50353_idx'), models.Index(fields=['user', 'created_at'], name='aplicacion__user_id_97a10e_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('restaurant', 'name')},
        ),
    ]
