# Generated by Django 5.2.6 on 2025-11-25 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, to='aplicacion.cuisine'),
        ),
        migrations.AddField(
            model_name='photo',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='aplicacion.restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='aplicacion.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aplicacion.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restauranttag',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.restaurant'),
        ),
        migrations.AddField(
            model_name='restauranttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tag'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='tags',
            field=models.ManyToManyField(blank=True, to='aplicacion.tag'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, through='aplicacion.RestaurantTag', to='aplicacion.tag'),
        ),
        migrations.AddField(
            model_name='dishtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tag'),
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, through='aplicacion.DishTag', to='aplicacion.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='dishtypealias',
            unique_together={('dish_type', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='restauranttag',
            unique_together={('restaurant', 'tag')},
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['restaurant', 'created_at'], name='aplicacion__restaur_35dcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['user', 'created_at'], name='aplicacion__user_id_d55a01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dishtag',
            unique_together={('dish', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('restaurant', 'name')},
        ),
    ]
