# Generated by Django 5.2.6 on 2025-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=300, upload_to='photos/'),
        ),
    ]
