# Generated by Django 5.2.6 on 2025-11-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
