# Generated by Django 5.2.6 on 2025-11-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_restaurantreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreview',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
    ]
