# Generated by Django 5.2.6 on 2025-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_restaurantreview_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreview',
            name='tags',
            field=models.ManyToManyField(blank=True, to='aplicacion.tag'),
        ),
    ]
