# Generated by Django 5.2.6 on 2025-11-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_restaurantreview_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
